name: antibody_dl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=3.0.0=py310h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2025.11.12=py310h06a4308_0
  - charset-normalizer=3.4.4=py310h06a4308_0
  - comm=0.2.3=py310h06a4308_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=py310h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gitdb=4.0.12=py310h06a4308_0
  - gitpython=3.1.45=py310h06a4308_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h5py=3.14.0=py310he0d80d8_0
  - hdf5=1.14.5=h2b7332f_2
  - idna=3.11=py310h06a4308_0
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_core=5.9.1=py310h06a4308_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.15.0=hc1efc7f_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.29=ha39b09d_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - ml_dtypes=0.5.1=py310hc74f9fe_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nomkl=3.0=0
  - numexpr=2.11.0=py310hbaae466_0
  - numpy=2.0.1=py310heeff2f4_1
  - numpy-base=2.0.1=py310h8a23956_1
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - openssl=3.0.17=h5eee18b_0
  - optree=0.14.1=py310hdb19cb5_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.2=py310h277b779_0
  - parso=0.8.5=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=5.9.0=py310h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_1
  - scikit-learn=1.7.1=py310hc74f9fe_0
  - scipy=1.15.3=py310h5e4e545_0
  - sentry-sdk=2.45.0=py310h06a4308_0
  - setproctitle=1.3.6=py310hb25bd0a_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - smmap=5.0.2=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py310h06a4308_0
  - sysroot_linux-64=2.17=h0157908_18
  - threadpoolctl=3.5.0=py310h7040dfc_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - wandb=0.16.6=pyhd8ed1ab_1
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cffi==2.0.0
      - click==8.3.1
      - deepmerge==2.0
      - defusedxml==0.7.1
      - distro==1.9.0
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - fastuuid==0.14.0
      - filelock==3.20.1
      - flatbuffers==25.9.23
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.67.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - importlib-metadata==8.7.0
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-ai==3.0.0b7
      - jupyter-ai-magics==3.0.0b7
      - jupyter-collaboration==4.2.0
      - jupyter-collaboration-ui==2.2.0
      - jupyter-docprovider==2.2.0
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==2.2.0
      - jupyter-ydoc==3.3.3
      - jupyterlab==4.5.1
      - jupyterlab-chat==0.17.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kagglehub==0.3.13
      - keras==3.12.0
      - keras-hub==0.24.0
      - lark==1.3.1
      - libclang==18.1.1
      - litellm==1.80.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mistune==3.1.4
      - multidict==6.7.0
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.5.0.50
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.27.7
      - nvidia-nvjitlink-cu12==12.9.86
      - openai==2.13.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==5.29.5
      - pycrdt==0.12.44
      - pycrdt-store==0.1.3
      - pycrdt-websocket==0.16.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlite-anyio==0.2.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-text==2.19.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.2
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/mhossai5/.conda/envs/antibody_dl
